
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 21;
  public static final int MOD = 7;
  public static final int AND = 18;
  public static final int PLUS = 8;
  public static final int OR = 19;
  public static final int LESS_EQUAL = 15;
  public static final int EQUAL = 11;
  public static final int RPARENT = 3;
  public static final int COS = 5;
  public static final int LBRACK = 20;
  public static final int NOT = 17;
  public static final int GREATER_EQUAL = 16;
  public static final int NOT_EQUAL = 12;
  public static final int GREATER = 14;
  public static final int EOL = 23;
  public static final int UMIN = 10;
  public static final int BOOLEAN = 24;
  public static final int COMMA = 22;
  public static final int LPARENT = 2;
  public static final int NUMBER = 25;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final int MIN = 9;
  public static final int LESS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPARENT",
  "RPARENT",
  "MULT",
  "COS",
  "DIV",
  "MOD",
  "PLUS",
  "MIN",
  "UMIN",
  "EQUAL",
  "NOT_EQUAL",
  "LESS",
  "GREATER",
  "LESS_EQUAL",
  "GREATER_EQUAL",
  "NOT",
  "AND",
  "OR",
  "LBRACK",
  "RBRACK",
  "COMMA",
  "EOL",
  "BOOLEAN",
  "NUMBER"
  };
}

